# Generated by Django 4.1.10 on 2023-09-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
