# Generated by Django 4.1.10 on 2023-10-05 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_customuser_options_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='forget_password_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
